### ISSUE TITLE
Using without gulp.src

### ISSUE THREAD

**Issue by gurmukhp** [ChadKillingsworth/closure-compiler-npm#16] opened 2016-03-30 10:39 UTC
Hi

I am trying to use this Gulp module without Gulp.src but having problems getting it to run.

If I try your first example with Gulp.src, I only have one file the compilation takes around 6 seconds. I'd like to try without Gulp.src to see if this can be shortened.

This works:
```js
var compilerPackage = require('google-closure-compiler');
var closureCompiler = compilerPackage.gulp();
gulp.task('js-compile', function() {
  return gulp.src('./dev/js/**/*.js')
      .pipe(closureCompiler({
          compilation_level: 'ADVANCED',
          warning_level: 'VERBOSE',
          output_wrapper: '(function(){\n%output%\n}).call(this)',
          js_output_file: 'output.min.js',
          debug: true
        }))
      .pipe(gulp.dest('./public/static/js/'));
});

[11:31:54] Using gulpfile ~/Sites/d4g/D4G/gulpfile.js
[11:31:54] Starting 'js-compile'...
[11:32:02] Finished 'js-compile' after 8.07 s

```

But this doesn't:
```js
var compilerPackage = require('google-closure-compiler');
var closureCompiler = compilerPackage.gulp();
gulp.task('js-compile', function() {
  return closureCompiler({
        js: './dev/js/**/*.js',
        externs: compilerPackage.compiler.CONTRIB_PATH + '/externs/jquery-1.9.js',
        compilation_level: 'ADVANCED',
        warning_level: 'VERBOSE',
        output_wrapper: '(function(){\n%output%\n}).call(this)',
        js_output_file: 'output.min.js'
      })
      .pipe(gulp.dest('./public/static/js/'));
});


[11:36:24] Using gulpfile ~/Sites/d4g/D4G/gulpfile.js
[11:36:24] Starting 'js-compile'...
```

For some reason, without Gulp.src, I'm never shown Finished js-compile.
Is there a way I can get some debug logs to see what's going on?

Thanks

**Comment by ChadKillingsworth** [comment] 2016-03-30 12:37
You would need to modify the source and add logging statements to it to get debug information. Gulp doesn't have the concept of `--verbose` that Grunt has.

However in this case the problem is probably because that closure-compiler globbing patterns are not the same as node's. Try:

```js
var compilerPackage = require('google-closure-compiler');
var closureCompiler = compilerPackage.gulp();
gulp.task('js-compile', function() {
  return closureCompiler({
        js: './dev/js/**.js',
        externs: compilerPackage.compiler.CONTRIB_PATH + '/externs/jquery-1.9.js',
        compilation_level: 'ADVANCED',
        warning_level: 'VERBOSE',
        output_wrapper: '(function(){\n%output%\n}).call(this)',
        js_output_file: 'output.min.js'
      })
      .pipe(gulp.dest('./public/static/js/'));
});
```

**Comment by Dominator008** [comment] 2016-03-30 15:50
I vaguely remember having this problem too. Can't get either of the original example or your example to work. I think the glob pattern was fixed in v20160208 and is unrelated here.

**Comment by ChadKillingsworth** [comment] 2016-03-30 15:55
This case has test coverage: https://github.com/ChadKillingsworth/closure-compiler-npm/blob/master/test/gulp.js#L218-L234

**Comment by Dominator008** [comment] 2016-03-30 15:57
@ChadKillingsworth This works for me:
```js
var gulp = require('gulp');
var compilerPackage = require('google-closure-compiler');
var closureCompiler = compilerPackage.gulp();

gulp.task('js-compile', function() {
  return gulp.src([])
      .pipe(closureCompiler({
        js: './dev/js/**/*.js',
        externs: compilerPackage.compiler.CONTRIB_PATH + '/externs/jquery-1.9.js',
        compilation_level: 'ADVANCED',
        warning_level: 'VERBOSE',
        output_wrapper: '(function(){\n%output%\n}).call(this)',
        js_output_file: 'output.min.js'
      }))
      .pipe(gulp.dest('./public/static/js/'));
});
```
Note the empty `gulp.src([])` part.

**Comment by Dominator008** [comment] 2016-03-31 18:35
@ChadKillingsworth Seems like the assertions are not being run.

**Closed** 2016-07-19 21:09 UTC
